### PR TITLE
Changed format of headlines

### PR DESCRIPTION
**Pull request by bennyn**
I improved the styles of our headlines to have better rendering in Markdown viewers such as [MarkdownPad](http://markdownpad.com/) or [DocumentUp](http://documentup.com/).

### CODE REVIEW

**Comment by caiogondim** [comment]
I'm still traveling and it's being difficult to do work while on my parent's house 😢 
Will be back to routine next Monday.

**Comment by bennyn** [comment]
No stress! Holidays are holidays. 🌝 🎈 🌈

**Comment by caiogondim** [comment]
Regarding documentation, what you think about using [Gitbook](https://www.gitbook.com/) and having a documentation similar to [Redux docs](http://redux.js.org/)?

**Comment by bennyn** [comment]
I am ok with Gitbook but what about changing the headlines in the README anyway?

**Comment by caiogondim** [comment]
Go for it!
Looks better to me 💅

**Comment by caiogondim** [comment]
Awesome!
Will make a minor release in a few minutes.

**Comment by bennyn** [comment]
:tada:

**Comment by bennyn** [comment]
But before a minor release we need the 2.0!

**Pull request merged**
