### PR TITLE
Added macOS environment

### PR DESCRIPTION
**Pull request by bennyn**
Added macOS for Travis testing to resolve https://github.com/caiogondim/logdown.js/issues/16.

### CODE REVIEW

**Comment by caiogondim** [comment]
Linux is enough for us. We are testing it against JS.
If it passes in Linux and not on macOS, it's not the library problem.
And we should use testing for correctness of the algorithm, not for E2E testing.

**Comment by caiogondim** [comment]
Regarding this topic, I'm very inclined to move all tests to Jest.

**Comment by bennyn** [comment]
So we can close this PR & https://github.com/caiogondim/logdown.js/issues/16 ?

**Comment by caiogondim** [comment]
Yes!
Let's strive to make things simple =)

**Comment by bennyn** [comment]
Ok! 🍻

**Pull request closed without merging**
