### PR TITLE
Added Logdown members in TypeScript declaration

### PR DESCRIPTION
**Pull request by bennyn**
A Logdown instance can have the following properties:

- markdown: Boolean
- prefix: String
- prefixColor: String

Please correct me if I forgot some!

### CODE REVIEW

**Comment by bennyn** [comment]
I think tests are failing because we lint external libraries? 
- https://travis-ci.org/caiogondim/logdown.js/jobs/183316473

**Comment by bennyn** [comment]
I filed a ticket at [is-number-like](https://github.com/vigour-io/is-number-like) which is used by "portscanner" which is used by "browser-sync" which is used by us. 😆 Because there was a minor change in "is-number-like" (changing `var` to `const`) which breaks our compatibility with Node.js v0.12. 

See here: https://github.com/vigour-io/is-number-like/blob/master/lib/index.js

Until this is fixed, we can lock the "browser-sync" version (which I did in this PR) to bypass the "is-number-like" issue.

**Comment by caiogondim** [comment]
We can drop support for Node v0.12 since it's not being maintained anymore

**Comment by caiogondim** [comment]
Would you consider this a patch or a minor release?

**Comment by bennyn** [comment]
Patch! :)

**Comment by caiogondim** [comment]
Done =)
- https://github.com/caiogondim/logdown.js/releases
- https://www.npmjs.com/package/logdown

**Comment by bennyn** [comment]
Perfect!! 🎉

**Pull request merged**
