### PR TITLE
Use latest 1.x version of Logdown.

### PR DESCRIPTION
**Pull request by bennyn**
[I submitted Logdown](https://github.com/jsdelivr/jsdelivr/pull/15749) to the [jsDelivr CDN](http://www.jsdelivr.com/) and we got accepted: http://www.jsdelivr.com/projects/logdown.js

With **jsDelivr** users can get all versions of Logdown through a very convenient CDN: https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/

Here are some possibilities:

```bash
http://cdn.jsdelivr.net/logdown.js/1.5.0/index.js    # Logdown v1.5.0 through HTTP
https://cdn.jsdelivr.net/logdown.js/1.5.0/index.js   # Logdown v1.5.0 through HTTPS
//cdn.jsdelivr.net/logdown.js/1.5.0/index.js         # Logdown v1.5.0 through HTTP or HTTPS
//cdn.jsdelivr.net/logdown.js/1.5/index.js           # Logdown v1.5.x
//cdn.jsdelivr.net/logdown.js/1/index.js             # Logdown v1.x.x
//cdn.jsdelivr.net/logdown.js/latest/index.js        # Logdown latest version
```

To use the latest and greatest version of Logdown in our demo page, I made this PR here.

### CODE REVIEW

**Comment by bennyn** [comment]
Travis should be configured that it only build if a `.travis.yml` is present: https://travis-ci.org/caiogondim/logdown.js/settings

**Comment by caiogondim** [comment]
I see value on putting the lib on a public CDN.

But don't see any in our use case.
We are just adding one more point of failure without any perceived value for the user.
And GitHub already uses a CDN for GitHub pages.

I vote for keeping it as simple as possible.

**Comment by bennyn** [comment]
I just wanted to make sure that we always demonstrate a Logdown version with the latest fixes included without the need to always update the `logdown.js` file manually.

**Comment by caiogondim** [comment]
The only concern I have is having the CDN down without us noticing.
Maybe we should link the JS on example page to the latest version on `dist/` folder?

**Comment by bennyn** [comment]
I agree with you that it's not good having another external dependency which could fail. So if we could point to the latest `dist/` folder, that would be great!

**Pull request closed without merging**
