### PR TITLE
Rename index.js -> logdown.js (Fixes #65)

### LINKED ISSUE #65: Rename "index.js" to "logdown.js"
Logdown's output for Bower is called `index.js`. When people execute `bower install logdown`, they get an `index.js` file out of the box, which need to be included the following way:

```html
<script src="/bower_components/logdown/dist/index.js"></script>
```

I think it would be nicer to have:

```html
<script src="/bower_components/logdown/dist/logdown.js"></script>
```

Especially if you have a Bower copy task which just dumps all files from "bower_components" into a flat hierarchy. This way logdown would not overwrite another library (which also might use the name `index.js`).

Other very famous libraries (like boostrap) also use their name as output (in this case [bootstrap.js](https://github.com/twbs/bootstrap/blob/v4-dev/bower.json#L19)).

**Logdown's current output:**

capture

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by bennyn** [comment]
Somehow it looks like the Karma test runner cannot find `Logdown`.  But the config from @lipis looks good to me: https://github.com/lipis/logdown.js/blob/master/test/karma-travisci.conf.js

**Comment by lipis** [comment]
https://github.com/lipis/logdown.js/blob/index/test/karma-travisci.conf.js

**Comment by bennyn** [comment]
@lipis I think I found the issue!

Please check this line: https://github.com/lipis/logdown.js/blob/index/test/server/constructor.js#L7

Logdown is included like this:

```javascript
var Logdown = require('../../src/')
```

It looks like that this pattern only works if the file inside is called `index.js`. If it's not the case, then Logdown should be included this way:

```javascript
var Logdown = require('../../src/logdown')
```

Can you please try if it resolves the problem? Please also check if there are more code paths where it says `var Logdown = require('../../src/logdown')`.

**Comment by bennyn** [comment]
On my second thought we should keep the Node.js paradigm and thus rename `src/logdown.js` back into `src/index.js`. This will make the tests pass and our output could still land in `dist/logdown.js`. WDYT?

**Comment by bennyn** [comment]
If this Pull Request gets merged, it will break builds for people who include Logdown with:

```html
<script src="/bower_components/logdown/dist/index.js"></script>
```

Because they need to switch to:

```html
<script src="/bower_components/logdown/dist/logdown.js"></script>
```

This is a breaking change so we need to publish a 2.x.x release if we follow [Semantic Versioning](http://semver.org/). 

@caiogondim Any opinions on this one?

**Comment by lipis** [comment]
Waiting for instructions.. yes it's a breaking change and my vote is for `logdown.js` instead of `index.js`

**Comment by caiogondim** [comment]
I don't think we should fear breaking compatibility if it's a minor thing.
Although I don't think as well we should break compatibility always.

I would vote to merge it and bump it to v2.

@lipis Care to do a release on npm? I can put you as contributor.

**Comment by bennyn** [comment]
@caiogondim As more and more people join this project we should write a Wiki page about the deployment process. Can you please add Wiki functionality to this project? Then I can go ahead and write about it. 😃

**Comment by caiogondim** [comment]
I prefer to use a `docs/` folder and put Markdown files there, to put everything inside a single git repo.
Wii feature is very coupled with GitHub.

**Comment by bennyn** [comment]
@caiogondim But then we can write these 3 lines also in the **README.md** itself.

Anyway... Guys it's 2017! 🎉 Time to release v2, no?

@lipis I agree with having `logdown.js` instead of `index.js`, so please go ahead. 😃

**Comment by lipis** [comment]
Squashed and synced with master..

**Comment by bennyn** [comment]
Cool! Now the only thing which is left is to change the imports in our tests. Like this one here:
- https://github.com/lipis/logdown.js/blob/index/test/server/constructor.js#L7

**Comment by lipis** [comment]
Le green! 💚

**Comment by bennyn** [comment]
Cool! 😎 

@caiogondim Should we merge it and do you want @lipis to make a 2.0.0 release?

@lipis Here are the steps to make a major release (following [semver](http://semver.org/)). You can do it, once you got the "power". 🔨  

```bash
npm version major
npm publish
git push
```

**Comment by bennyn** [comment]
@caiogondim Should we get this in?

**Comment by caiogondim** [comment]
Let's do this 🎉

**Comment by lipis** [comment]
woho!! 🎆

**Comment by caiogondim** [comment]
@lipis You managed to make a new release?

**Pull request merged**
