### PR TITLE
Improve markdown parsing

### LINKED ISSUE #38: Escaping special characters
```
call the `foo\_bar` method on the `quux\_service` endpoint
```

rendersas 

call the `foo\`_bar method on the quux\_`service` endpoint

### PR DESCRIPTION
**Pull request by SleepWalker**
This PR fixes #38 

But before accepting it, probably we should a little bit discuss it.

The parser is partially based on [this spec](http://spec.commonmark.org/0.28/#inlines). It takes 100+ lines of code and adds 0.33kb to dist size.

The reason why it takes so much is because of nesting, escaping support and also because of some edge cases, which can not be achieved using only js regexp. We can a little bit reduce parser size if we drop nesting support (which is actually currently broken in browser due to bad styles order e.g.: `console.log('%c%cfoo%c%c', 'font-weight: bold;', '', 'font-style:italic;', '')` for `logger.log('*_foo_*')`). What do you think? (@caiogondim , @bennyn )

There is one more feature, that looks interesting to me, but I've skipped it to keep code a little bit simpler. But if you think, that we need it, I can implement it too. Please see this test case:

```js
xit('should not format snake_case words', () => { // do we really need this?
  expect(markdown.parse('foo_bar_')).toBe('foo_bar_')
  expect(markdown.parse('_foo_bar')).toBe('_foo_bar')

  expect(markdown.parse('_*te_st*')).toBe('_<b>te_st</b>')
  expect(markdown.parse('_*te_st*_')).toBe('<i><b>te_st</b></i>')
})
```

BTW. In my console on linux `chalk.italic` looks almost the same as the normal text.

### CODE REVIEW

**Comment by caiogondim** [comment]
That's just great.
Rewriting the Markdown parser is something that was on my backlog since a long time.

Regarding the skipped test case, it makes sense for me, especially for printing code:
```markdown.parse('`SOME_REDUX_ACTION`') // want it to be expected as code only, not as italic inside code```

Or maybe the user should explicitly escape characters it doesn't want to be interpreted as markdown tokens. And right escaping don't work. I like the latter better. Explicit `>` implicit.

What are your thoughts?

And great PR again :tada:

**Comment by SleepWalker** [comment]
Current parser implementation already supports escaping and it completely
ignores markdown (and escape chars too) inside `code` spans.

The skipped test is only about the case, when user uses italic and expects
markdown to be ignored inside variable names in snaked case naming style.
In order to support such case we need to implement additional rules only
for italic (detect left and right flanking delimiters). I think, that this
rule is not so important to spend the bytes on it's implementation, because
I expect developers to use code spans for displaying code, instead of
italic :)

**Comment by caiogondim** [comment]
> Current parser implementation already supports escaping and it completely ignores markdown (and escape chars too) inside `code` spans.
I created an example to better illustrate this https://runkit.com/caiogondim/5a3aca00b147010012535bfb

**Comment by SleepWalker** [comment]
The parser from this PR will produce:

```html
`SOME\_REDUX\_ACTION` => <code>SOME\_REDUX\_ACTION</code>
`OTHER_REDUX_ACTION` => <code>OTHER_REDUX_ACTION</code>

but

*SOME\_REDUX\_ACTION* => <b>SOME_REDUX_ACTION</b>
*OTHER_REDUX_ACTION* => <b>OTHER<i>REDUX</i>ACTION</b>
(if I'll make the skipped test to pass it should produce: <b>OTHER_REDUX_ACTION</b>)

_SOME\_REDUX\_ACTION_ => <i>SOME_REDUX_ACTION</i>
_OTHER_REDUX_ACTION_ => <i>OTHER</i>REDUX<i>ACTION</i>
(if I'll make the skipped test to pass it should produce: <i>OTHER_REDUX_ACTION</i>)
```

So the code spans are work as expected, but the `_` may be improved (but I'm not sure if this improvement critical for purposes of logging lib. You should simply properly use md and wrap all the code into the `code span` instead of *italics* etc.)

**Comment by SleepWalker** [comment]
Sorry, that was a miss click :D

**Comment by caiogondim** [comment]
@SleepWalker Again, that was a beautiful PR 👏 👏 👏

**Pull request merged**
